[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#686868"
blue = "#59C2FF"
cyan = "#95E6CB"
green = "#C2D94C"
magenta = "#FFEE99"
red = "#F07178"
white = "#FFFFFF"
yellow = "#FFB454"

[colors.normal]
black = "#01060E"
blue = "#53BDFA"
cyan = "#90E1C6"
green = "#91B362"
magenta = "#FAE994"
red = "#EA6C73"
white = "#C7C7C7"
yellow = "#F9AF4F"

[colors.primary]
background = "#000000"
foreground = "#fff6a6"

[font]
size = 14.0

[font.bold]
family = "Fira Code"
style = "Bold"

[font.bold_italic]
family = "Fira Code"
style = "Regular"

[font.italic]
family = "Fira Code"
style = "Light"

[font.normal]
family = "Fira Code"
style = "Retina"

[scrolling]
history = 25000
multiplier = 5
